### ISSUE TITLE
Contributor badge changes

### ISSUE THREAD

**Issue by agamm** [agamm/awesome-developer-first#131]
I don't want to see the contributor count, but the amount of stars - plus I'd like it to link to the github too.

**Comment by fmerian** [comment]
agreed. for the record, related: #87.

**Comment by fmerian** [comment]
preview:

* [Plausible](https://plausible.io/) - Simple, privacy-friendly, and open-source web analytics tool. [![Plausible](https://img.shields.io/github/stars/plausible/analytics?style=flat-square&logo=github&labelColor=%230D1117&color=%23161B22)](https://github.com/plausible/analytics)

```markdown
* [Plausible](https://plausible.io/) - Simple, privacy-friendly, and open-source web analytics tool. [![Plausible](https://img.shields.io/github/stars/plausible/analytics?style=flat-square&logo=github&labelColor=%230D1117&color=%23161B22)](https://github.com/plausible/analytics)
```

wdyt @agamm?

**Comment by fmerian** [comment]
I'll handle it
