### ISSUE TITLE
Sort products alphabetically?

### ISSUE THREAD

**Issue by fmerian** [agamm/awesome-developer-first#53]
Quick suggestion: how about sorting products alphabetically? It would ease the read, making it (a little) more awesome?

**Comment by agamm** [comment]
The only problem I have with that is that there would be no indication of when a product was added. Do you think that it is more important?

**Comment by fmerian** [comment]
Yes, I think it would make more sense. At least, it would give more structure to the list. You can always refer to the [latest commits here](https://github.com/agamm/awesome-developer-first/commits/main).

**Comment by agamm** [comment]
Done, thanks @fmerian 

https://github.com/agamm/awesome-developer-first/commit/2d75bca5097b1196730e7e187c577f4642ae3648
