### ISSUE TITLE
Add Graphite

### ISSUE THREAD

**Issue by benschac** [agamm/awesome-developer-first#68]
tools:
- graphite.dev
- https://sapling-scm.com/
- https://www.phacility.com/phabricator/

https://twitter.com/acdlite/status/1255640994239766528?lang=en

**Comment by agamm** [comment]
What is a "stack" in this context exactly?

**Comment by benschac** [comment]
A stack of PRs. Each PR is one atomic commit that does one single thing.

Here are graphite's docs that are more up-to-date.

https://graphite.dev/docs/why-use-stacked-changes

Other examples today of open source projects using stacked changes:
- LLVM: https://reviews.llvm.org/ (phabricator)
- https://phabricator.wikimedia.org/ (phabricator)

**Comment by agamm** [comment]
Learned something new, thanks @benschac, I'll probably write about it on unzip.dev ;)

Wanna create a PR for it with 2 or more products? (Note that they need to be monetized to be considered a product).

**Comment by benschac** [comment]
I don't have time to contribute, feel free to add anything here if it's helpful!

**Comment by fmerian** [comment]
if we want to add this new category, we need to review tools first, to make sure they fit with the [requirements](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md).

> Terms of relevant products:
> - Abundantly clear that is marketed for developers.
> - "Headless", "API-First", "SaaS" are frequently used keywords.
> - Usually this means that the front page has some code examples :)
> - Products - tools/services that people pay for.

suggested tools by @benschac:
> https://graphite.dev
> https://sapling-scm.com/
> https://www.phacility.com/phabricator/

**Comment by fmerian** [comment]
- Graphite looks like a great product indeed. however, there's no pricing for now ([Graphite is in beta](https://app.graphite.dev/join-waitlist)).
- Sapling is an open-source project, e.g. not relevant for this repo.
- Phacility is no longer actively maintained.


I'd love to add Graphite when pricing or paid-route on the main landing page will be more indicative -- like we did for Lago (#54).

thoughts @agamm?

**Comment by fmerian** [comment]
closing for now until public launch
