### ISSUE TITLE
create PR template

### ISSUE THREAD

**Issue by fmerian** [agamm/awesome-developer-first#72]
despite the [contribution guidelines](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md), we had some back-and-forth conversations in recent PRs (#63, #67, #69). 

so, what do you think of a [PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) with ticking boxes to help with new contributions?

## suggestion

```
[Insert URL to the product here.]

## checklist

Please make sure you've complied with the below requirements:

- [ ] I've read the [contribution guidelines](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md) and I'm confident my suggestion is relevant.
- [ ] The PR has a descriptive title -- e.g., `Add {product}`, not `Update README.md`.
- [ ] The new submission isn't a duplicate.
- [ ] The entry has a description, is sorted alphabetically, and ends with a full stop.
```

**Comment by agamm** [comment]
Looks great! I like the idea.

**Comment by fmerian** [comment]
#76 currently in review
