### ISSUE TITLE
New category: Internal tools

### ISSUE THREAD

**Issue by fmerian** [agamm/awesome-developer-first#79]
for tools like: 

- Interval (already in [Misc](https://github.com/agamm/awesome-developer-first#misc)), 
- Appsmith, and 
- Retool.

wdyt?

edit: suggestion:
```
* [Appsmith](https://www.appsmith.com/) - Open-source framework to build admin panels, internal tools, and dashboards.
* [Interval](https://interval.com/) - SDK to build internal tools and scripts for your product.
* [Retool](https://retool.com/) - Build internal tools with rich user interfaces and PostgreSQL database.
```

**Comment by Jogai** [comment]
Dont forget budibase, nocodb, illa cloud, tooljet, openblocks, rei3, knack, airtable, caspio, quickbase, zoho creator, bubble and probably some others I missed ;)

**Comment by fmerian** [comment]
> Dont forget budibase, nocodb, illa cloud, tooljet, openblocks, rei3, knack, airtable, caspio, quickbase, zoho creator, bubble and probably some others I missed ;)

are they all developer-first?

**Comment by Jogai** [comment]
Well, some are positioning themselves as a Retool alternative, so if Retool is, then these are too.

**Comment by fmerian** [comment]
> Well, some are positioning themselves as a Retool alternative, so if Retool is, then these are too.

is Retool a good candidate for this repo from your point of view? IMO the objective here isn't to list all existing products and competitors, just awesome developer-first products :)

**Comment by agamm** [comment]
I do really love internal/low-code/no-code tools (especially Retool). But I think we should delegate this to something like: https://github.com/kairichard/awesome-nocode-lowcode

No reason to confuse people here. Let's try to be more strict with the definition.
@fmerian Let's close?

**Comment by fmerian** [comment]
agree -- closing the issue
